apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - name: notebook
          image: jupyter/base-notebook:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  type: NodePort  # or ClusterIP/LoadBalancer
  selector:
    app: jupyter-notebook
  ports:
    - port: 8888
      targetPort: 8888
