apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
        - name: jupyter
          image: "{{ image }}"
          ports:
            - containerPort: {{ port }}
          resources:
            requests:
              cpu: "{{ cpu_request }}"
              memory: "{{ memory_request }}"
            limits:
              cpu: "{{ cpu_limit }}"
              memory: "{{ memory_limit }}"
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: keda
spec:
  selector:
    app: jupyter-notebook
  ports:
    - protocol: TCP
      port: {{ port }}
      targetPort: {{ port }}
  type: NodePort
