apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jupyter-scaler
  namespace: keda
spec:
  scaleTargetRef:
    name: jupyter-notebook
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.kafka.svc.cluster.local:9092
        topic: jupyter-events
        consumerGroup: keda-group
        lagThreshold: "5"
